repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
        name: Check YAML (unsafe)
        args: [--unsafe]
        files: &non-standard-yaml-files .gitlab-ci.yml
      # check other yaml files normally
      - id: check-yaml
        exclude: *non-standard-yaml-files
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.1
    hooks:
      - id: ruff
        args: ["--fix"] # Attempt to in-place fix issues.
      - id: ruff-format
